#!/usr/bin/env bash
#
# Regenerates app/data/stock-icons.txt: the symbolic icon names that Adwaita has, outside its
# "legacy" folder, in both the oldest version the packages run on (Debian bookworm's 43, which the
# AppImage bundles) and the newest one (whatever Debian ships). The app may only use names from
# that list, icons it bundles itself (app/data/icons/) or libadwaita's own `adw-` icons; the
# `icons_every_icon_the_app_uses_is_in_the_theme` scenario checks that. A legacy or dropped name
# is drawn from some other icon set (a full-colour icon, as the flatpak's Library tab once was)
# or as a "missing icon" placeholder, depending on the system.
#
# Usage: scripts/update-stock-icons.sh [OLDEST_VERSION] [NEWEST_VERSION]
#        (Debian package versions; defaults below)

set -euo pipefail

OLDEST="${1:-43-1}"
NEWEST="${2:-51.0-1}"
POOL="https://deb.debian.org/debian/pool/main/a/adwaita-icon-theme"
REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
OUT="$REPO_ROOT/app/data/stock-icons.txt"

names() {
    curl -fsSL --retry 3 "$POOL/adwaita-icon-theme_$1_all.deb" \
        | dpkg-deb --fsys-tarfile /dev/stdin \
        | tar -t \
        | grep -v '/legacy/' \
        | grep -oE '[a-z0-9-]+-symbolic\.svg$' \
        | sed 's/\.svg$//' \
        | sort -u
}

{
    echo "# Adwaita symbolic icons present (outside legacy/) in both $OLDEST and $NEWEST."
    echo "# Generated by scripts/update-stock-icons.sh; don't edit by hand."
    comm -12 <(names "$OLDEST") <(names "$NEWEST")
} > "$OUT"
echo "wrote $(grep -vc '^#' "$OUT") names to $OUT"
